extern uint16_t dialogue_index;
extern uint8_t dialogue_remaining;

extern void display_dialogue(uint16_t, uint8_t, uint8_t, const char[][8]);

#define TXT_INTRO 0
#define TXT_INTRO_LEN 6

#define TXT_SDW_INTRO 228
#define TXT_SDW_INTRO_LEN 5

#define TXT_SDW_CATPAW 460
#define TXT_SDW_CATPAW_LEN 0

#define TXT_SLAVER 483
#define TXT_SLAVER_LEN 0

#define TXT_GIRL_THX 523
#define TXT_GIRL_THX_LEN 2

#define TXT_SDW_BATTLE 603
#define TXT_SDW_BATTLE_LEN 0

#define TXT_SDW_WIN 646
#define TXT_SDW_WIN_LEN 0

#define TXT_GIRL_FATHER 685
#define TXT_GIRL_FATHER_LEN 0

#define TXT_ENEMY 718
#define TXT_ENEMY_LEN 0

#define TXT_FATHER 734
#define TXT_FATHER_LEN 3

#define TXT_SDW_SHIP 892
#define TXT_SDW_SHIP_LEN 2

#define TXT_NSE_THX 1008
#define TXT_NSE_THX_LEN 3

#define TXT_SDW_RETURN 1124
#define TXT_SDW_RETURN_LEN 0

#define TXT_NSE_SUSPICIOUS 1155
#define TXT_NSE_SUSPICIOUS_LEN 1

#define TXT_NSE_CHAOS 1220
#define TXT_NSE_CHAOS_LEN 1

#define TXT_MAD_ESCAPED 1260
#define TXT_MAD_ESCAPED_LEN 0

#define TXT_NSE_WHY 1275
#define TXT_NSE_WHY_LEN 0

#define TXT_MAD_OFFER 1300
#define TXT_MAD_OFFER_LEN 1

#define TXT_NSE_SPREAD 1351
#define TXT_NSE_SPREAD_LEN 0

#define TXT_MAD_MISHAP 1376
#define TXT_MAD_MISHAP_LEN 1

#define TXT_NSE_MONSTER 1411
#define TXT_NSE_MONSTER_LEN 0

#define TXT_NSE_CONFRONT 1423
#define TXT_NSE_CONFRONT_LEN 0

#define TXT_SDW_TOWER 1472
#define TXT_SDW_TOWER_LEN 1

#define TXT_LDR_ANTS 1527
#define TXT_LDR_ANTS_LEN 0

#define TXT_NSE_PAY 1564
#define TXT_NSE_PAY_LEN 0

#define TXT_LDR_CLEAN 1594
#define TXT_LDR_CLEAN_LEN 0

#define TXT_NSE_DESTROY 1632
#define TXT_NSE_DESTROY_LEN 0

#define TXT_SDW_VICTORY 1655
#define TXT_SDW_VICTORY_LEN 2

#define TXT_NSE_VICTORY 1734
#define TXT_NSE_VICTORY_LEN 0

#define TXT_ENDING 1772
#define TXT_ENDING_LEN 3

#define TXT_BAR 1905
#define TXT_BAR_LEN 0

#define TXT_FIGHTER 1934
#define TXT_FIGHTER_LEN 1

#define TXT_MUTINY 1964
#define TXT_MUTINY_LEN 0

#define TXT_MUTINEER 2005
#define TXT_MUTINEER_LEN 0

#define TXT_CAPTAIN_THX 2022
#define TXT_CAPTAIN_THX_LEN 0

#define TXT_RATS 2051
#define TXT_RATS_LEN 0

#define TXT_MEGARAT 2089
#define TXT_MEGARAT_LEN 0

#define TXT_RAT_THX 2121
#define TXT_RAT_THX_LEN 0

#define TXT_SNOBS 2149
#define TXT_SNOBS_LEN 0

#define TXT_RICH 2171
#define TXT_RICH_LEN 0

#define TXT_SNOB_WOW 2186
#define TXT_SNOB_WOW_LEN 0

#define TXT_WARES 2222
#define TXT_WARES_LEN 1

#define TXT_WARES_THX 2274
#define TXT_WARES_THX_LEN 0
